stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Merhaba Build"

job_test:
  stage: test
  script:
    - echo "Merhaba Test"

job_deploy:
  stage: deploy
  script:
    - echo "Merhabalar Deploy"