stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Merhaba Build"

job_test:
  stage: test
  script:
    - echo "Merhaba Test"

job_deploy:
  stage: deploy
  script:
    - echo "Merhabalar Deploy"

include:
  - local: 'ci_configs/prod/.gitlab-ci.yml'
  - local: 'ci_configs/dev/.gitlab-ci.yml'