stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Merhaba Build Prod"

job_test:
  stage: test
  script:
    - echo "Merhaba Test Prod"

job_deploy:
  stage: deploy
  script:
    - echo "Merhabalar Deploy Prod"