stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Merhaba Build Dev "

job_test:
  stage: test
  script:
    - echo "Merhaba Test Dev "

job_deploy:
  stage: deploy
  script:
    - echo "Merhabalar Deploy Dev "